### ISSUE TITLE
Alternate Arduino Board Support

### ISSUE THREAD

**Issue by baqwas** [alexchang0229/SatelliteTracker#2]
Would an ESP8266 board work equally well for the tracking part? Would like to push tracking data to the board without manual changes to the code. Thanks.

P.S. Of course, will always power the stepper motors with independent power source but common ground. :)

Kind regards.

**Comment by alexchang0229** [comment]
I think that would work, I'm guessing you mean setup an ESP8266 as a webserver and give ti the TLEs through there? One thing to note is that in the code I do use the real time clock (RTC) on the MKR 1000 to keep the time, so if you want to use another board, try to find one with an RTC.

Let me know if you do decide to try it!

**Comment by baqwas** [comment]
Thx, @alexchang0229. Will definitely keep you posted. However, I'll start with MKR1000 and use the u-blox GPS module before working with the ESP8266. I have all the electronic parts except for the second motor driver board (the 3D printing output will not be delivered before Wed, 7/22). I always seem to run out of suitable pins for even modest solutions on the ESP8266 (the usual environment monitoring projects). Once again, many, many thanks for making it simple for us to follow your footsteps.

Kind regards.
